import createClient, { Middleware } from 'openapi-fetch'
import type { paths } from './generated' // generated by openapi-typescript

function mkAuthMiddleware(apiKey: string): Middleware {
  const authMiddleware: Middleware = {
    async onRequest({ request }) {
      request.headers.set('X-OPTIX-API-KEY-V2', apiKey)
      return request
    },
  }
  return authMiddleware
}

export function newClient(apiKey: string) {
  const client = createClient<paths>({
    baseUrl: 'https://publicapi.optix.co.uk/v1/',
  })
  const authMiddleware = mkAuthMiddleware(apiKey)

  client.use(authMiddleware)
  return client
}
