import { newClient } from './client'
import type { components } from './generated' // generated by openapi-typescript

export enum ProductType {
  Frame = 'Frame',
  Sunglasses = 'Sunglasses',
  MiscItem = 'Misc Item',
}

type ProductSearchRequest = components['schemas']['ProductSearchRequest']

export type ProductSearchInput = ProductSearchRequest & {
  productType: ProductType
}

// const {
//   data, // only present if 2XX response
//   error, // only present if 4XX or 5XX response
// } = await client.GET('/blogposts/{post_id}', {
//   params: {
//     path: { post_id: '123' },
//   },
// })

export async function searchProducts(
  client: ReturnType<typeof newClient>,
  input: ProductSearchInput
) {
  const response = await client.POST('/v1/product/search/{ProductType}', {
    params: {
      path: {
        ProductType: input.productType,
      },
    },
    body: input,
  })
  return response
}
