import { newAuthenticatedClient } from './client'
import type { components } from '../generated' // generated by openapi-typescript
import { ApiResponse, fromClientResponse, toExn } from '../response'

export enum ProductType {
  Frame = 'Frame',
  Sunglasses = 'Sunglasses',
  MiscItem = 'Misc Item',
}

export type ProductSearchRequest = components['schemas']['ProductSearchRequest']
export type ProductSearchInput = ProductSearchRequest & {
  productType: ProductType
}
export type ProductSearchResponse = components['schemas']['QueryProductDetailsResponseIPagedResult']

export async function productsSearch(
  client: ReturnType<typeof newAuthenticatedClient>,
  input: ProductSearchInput
): Promise<ApiResponse<ProductSearchResponse>> {
  const response = await client.POST('/v1/product/search/{ProductType}', {
    params: {
      path: {
        ProductType: input.productType,
      },
    },
    body: input,
  })
  return fromClientResponse(response)
}

export async function productsSearchExn(
  client: ReturnType<typeof newAuthenticatedClient>,
  input: ProductSearchInput
): Promise<ProductSearchResponse> {
  const response = await productsSearch(client, input)
  return toExn(response)
}


export type ProductGetSkusInput = components['schemas']['QueryProductSkusRequest']
export type ProductGetSkusResponse = components['schemas']['QueryProductSkusResponse']

export async function productGetSkus(
  client: ReturnType<typeof newAuthenticatedClient>,
  input: ProductGetSkusInput
): Promise<ApiResponse<ProductGetSkusResponse>> {
  const response = await client.POST('/v1/product/skus', {
    body: input,
  })
  return fromClientResponse(response)
}

export async function productGetSkusExn(
  client: ReturnType<typeof newAuthenticatedClient>,
  input: ProductGetSkusInput
): Promise<ProductGetSkusResponse> {
  const response = await productGetSkus(client, input)
  return toExn(response)
}

export type ProductGetPricesInput = components['schemas']['QueryBatchProductPriceRequest']
export type ProductGetPricesResponse = components['schemas']['ProductBatchPriceResponse']

export async function productGetPrices(
  client: ReturnType<typeof newAuthenticatedClient>,
  input: ProductGetPricesInput
): Promise<ApiResponse<ProductGetPricesResponse>> {
  const response = await client.POST('/v1/product/prices', {
    body: input,
  })
  return fromClientResponse(response)
}

export async function productGetPricesExn(
  client: ReturnType<typeof newAuthenticatedClient>,
  input: ProductGetPricesInput
): Promise<ProductGetPricesResponse> {
  const response = await productGetPrices(client, input)
  return toExn(response)
}


export type SkuRetailPriceRequest = components['schemas']['SkuRetailPriceRequest']

export type ProductGetRetailPricesInput = {
  priceRequests?: SkuRetailPriceRequest[]
}
export type ProductGetRetailPricesResponse = components['schemas']['SkuRetailPriceResponse'][]

export async function productGetRetailPrices(
  client: ReturnType<typeof newAuthenticatedClient>,
  input: ProductGetRetailPricesInput
): Promise<ApiResponse<ProductGetRetailPricesResponse>> {
  const response = await client.POST('/v1/product/retail-prices', {
    body: input,
  })
  return fromClientResponse(response)
}

export async function productGetRetailPricesExn(
  client: ReturnType<typeof newAuthenticatedClient>,
  input: ProductGetRetailPricesInput
): Promise<ProductGetRetailPricesResponse> {
  const response = await productGetRetailPrices(client, input)
  return toExn(response)
}



